/* ============================================================================
 * i18n.js — ChessTrophies internationalization (curated-dictionary approach).
 *
 * A tiny, dependency-free, CSP-safe (no inline handlers, same-origin) i18n
 * layer for the vanilla-JS SPA. Loaded as a classic global IIFE BEFORE app.js
 * so `window.CT_i18n.t()` is available everywhere.
 *
 * HOW IT WORKS
 *   - Static markup is tagged with `data-i18n` (textContent), `data-i18n-ph`
 *     (placeholder) or `data-i18n-aria` (aria-label). On boot + on every
 *     language change we walk those nodes and swap in the active translation.
 *   - Dynamic strings call `CT_i18n.t('key', {vars})` directly.
 *   - The active language is detected from localStorage('ct_lang') -> the
 *     account's saved `language` -> navigator.language -> 'en'. It's also
 *     stored per-account (rides the /api/progress sync, like the board theme)
 *     so it follows the user across devices.
 *   - Arabic + Urdu flip the document to RTL (`dir="rtl"`).
 *
 * BRAND RULE: "ChessTrophies" and "playchesstrophies.com" ALWAYS stay in
 * English in every language — they are a brand name, never a translatable
 * string. They live OUTSIDE any data-i18n node (e.g. the auth <h1>), and every
 * translator dictionary preserves them verbatim where they appear inline.
 *
 * COVERAGE: curated, high-traffic screens — the welcome / create-account flow,
 * the bottom nav, and the Settings ("options") menu — exactly the surfaces the
 * language picker touches. Untranslated keys fall back to English, so partial
 * coverage never shows a blank. Expand the dictionaries to widen coverage.
 * ==========================================================================*/
(function () {
  'use strict';

  // Language registry: code -> native display name (+ dir for RTL scripts).
  // English first (source/fallback). Order = how the picker lists them.
  var LANGS = [
    { code: 'en', name: 'English' },
    { code: 'es', name: 'Español' },
    { code: 'pt', name: 'Português' },
    { code: 'fr', name: 'Français' },
    { code: 'de', name: 'Deutsch' },
    { code: 'it', name: 'Italiano' },
    { code: 'ru', name: 'Русский' },
    { code: 'zh', name: '中文' },
    { code: 'ja', name: '日本語' },
    { code: 'id', name: 'Bahasa Indonesia' },
    { code: 'tl', name: 'Tagalog' },
    { code: 'hi', name: 'हिन्दी' },
    { code: 'bn', name: 'বাংলা' },
    { code: 'ta', name: 'தமிழ்' },
    { code: 'te', name: 'తెలుగు' },
    { code: 'mr', name: 'मराठी' },
    { code: 'gu', name: 'ગુજરાતી' },
    { code: 'kn', name: 'ಕನ್ನಡ' },
    { code: 'ml', name: 'മലയാളം' },
    { code: 'pa', name: 'ਪੰਜਾਬੀ' },
    { code: 'ar', name: 'العربية', dir: 'rtl' },
    { code: 'ur', name: 'اردو', dir: 'rtl' }
  ];

  var STORE_KEY = 'ct_lang';

  // ---- Dictionaries -------------------------------------------------------
  // English is the canonical source. Keep emoji + leading glyphs (▶, 🎨, …) in
  // the value; translators preserve them. {vars} are interpolation slots.
  var EN = {
    // Bottom nav
    'nav.play': 'Play',
    'nav.puzzles': 'Puzzles',
    'nav.trophies': 'Trophies',
    'nav.rankings': 'Rankings',
    'nav.profile': 'Profile',

    // Welcome / auth screen
    'auth.tagline': 'Play the computer, solve daily puzzles, build streaks, earn trophies.',
    'auth.playNow': '▶ Play now',
    'auth.playNowHint': 'No sign-up — jump straight into a game vs the computer.',
    'auth.accountPrompt': 'Want to save your progress across devices?',
    'auth.tabSignIn': 'Sign in',
    'auth.tabCreate': 'Create account',
    'auth.emailOrUsername': 'Email or username',
    'auth.password': 'Password',
    'auth.signInBtn': 'Sign in',
    'auth.forgotPassword': 'Forgot password?',
    'auth.username': 'Username',
    'auth.email': 'Email',
    'auth.regionLabel': 'Region (city, country)',
    'auth.optionalDash': '— optional',
    'auth.regionPlaceholder': 'Optional — e.g. Austin, USA',
    'auth.skillSummary': 'Set a starting rating (optional)',
    'auth.skillLabel': 'Skill level',
    'auth.skillNew': 'New to chess – 400',
    'auth.skillBeginner': 'Beginner – 800',
    'auth.skillIntermediate': 'Intermediate – 1200',
    'auth.skillAdvanced': 'Advanced – 1600',
    'auth.eloHelp': 'Leave this and we’ll start you at Beginner — your rating adjusts as you play.',
    'auth.createBtn': 'Create account',
    'auth.languageLabel': 'Language',
    'auth.or': 'or',
    'auth.continueGuest': 'Continue as guest',
    'auth.guestHint': 'No sign-up — go to the home screen to explore. Progress saves on this device; create an account to keep it across devices.',
    'auth.crossDevice': 'Your account is securely stored on our servers, so your rating and trophies follow you across devices. Usernames are unique across every platform.',

    // Settings ("options") menu
    'settings.title': 'Settings',
    'settings.appearance': '🎨 Appearance',
    'settings.boardTheme': 'Board Theme',
    'settings.pieceStyle': 'Piece Style',
    'settings.language': '🌍 Language',
    'settings.languageHint': 'Choose your language. Chat with players in other languages still works — the playchesstrophies.com brand name always stays in English.',
    'settings.profile': '👤 Profile',
    'settings.changePic': '🖼️  Change Profile Picture',
    'settings.viewProfile': '✏️  View My Profile',
    'settings.notifications': '🔔 Notifications',
    'settings.gameSounds': 'Game sounds',
    'settings.account': '⚙️ Account',
    'settings.themeSavedNote': 'Your theme and language are saved to your profile — they stay the same every time you sign in.',
    'settings.changePassword': '🔑  Change Password',
    'settings.signOut': 'Sign Out',

    // Toasts / misc shared
    'toast.langChanged': 'Language updated 🌍'
  };

  var ES = {
    'nav.play': 'Jugar',
    'nav.puzzles': 'Problemas',
    'nav.trophies': 'Trofeos',
    'nav.rankings': 'Clasificación',
    'nav.profile': 'Perfil',

    'auth.tagline': 'Juega contra la computadora, resuelve problemas diarios, crea rachas y gana trofeos.',
    'auth.playNow': '▶ Jugar ahora',
    'auth.playNowHint': 'No necesitas registrarte: empieza una partida contra la computadora con un toque.',
    'auth.accountPrompt': '¿Quieres guardar tu progreso en todos tus dispositivos?',
    'auth.tabSignIn': 'Iniciar sesión',
    'auth.tabCreate': 'Crear cuenta',
    'auth.emailOrUsername': 'Correo o nombre de usuario',
    'auth.password': 'Contraseña',
    'auth.signInBtn': 'Iniciar sesión',
    'auth.forgotPassword': '¿Olvidaste tu contraseña?',
    'auth.username': 'Nombre de usuario',
    'auth.email': 'Correo electrónico',
    'auth.regionLabel': 'Región (ciudad, país)',
    'auth.optionalDash': '— opcional',
    'auth.regionPlaceholder': 'Opcional — p. ej. Austin, EE. UU.',
    'auth.skillSummary': 'Elegir una puntuación inicial (opcional)',
    'auth.skillLabel': 'Nivel de habilidad',
    'auth.skillNew': 'Nuevo en el ajedrez – 400',
    'auth.skillBeginner': 'Principiante – 800',
    'auth.skillIntermediate': 'Intermedio – 1200',
    'auth.skillAdvanced': 'Avanzado – 1600',
    'auth.eloHelp': 'Déjalo así y empezarás como Principiante: tu puntuación se ajusta a medida que juegas.',
    'auth.createBtn': 'Crear cuenta',
    'auth.languageLabel': 'Idioma',
    'auth.or': 'o',
    'auth.continueGuest': 'Continuar como invitado',
    'auth.guestHint': 'Sin registro. Tu progreso se guarda en este dispositivo; crea una cuenta para conservarlo en todos tus dispositivos.',
    'auth.crossDevice': 'Tu cuenta se guarda de forma segura en nuestros servidores, así que tu puntuación y trofeos te acompañan en todos los dispositivos. Los nombres de usuario son únicos en todas las plataformas.',

    'settings.title': 'Configuración',
    'settings.appearance': '🎨 Apariencia',
    'settings.boardTheme': 'Tema del tablero',
    'settings.pieceStyle': 'Estilo de piezas',
    'settings.language': '🌍 Idioma',
    'settings.languageHint': 'Elige tu idioma. El chat con jugadores de otros idiomas sigue funcionando; la marca playchesstrophies.com siempre se mantiene en inglés.',
    'settings.profile': '👤 Perfil',
    'settings.changePic': '🖼️  Cambiar foto de perfil',
    'settings.viewProfile': '✏️  Ver mi perfil',
    'settings.notifications': '🔔 Notificaciones',
    'settings.gameSounds': 'Sonidos del juego',
    'settings.account': '⚙️ Cuenta',
    'settings.themeSavedNote': 'Tu tema e idioma se guardan en tu perfil: se mantienen iguales cada vez que inicias sesión.',
    'settings.changePassword': '🔑  Cambiar contraseña',
    'settings.signOut': 'Cerrar sesión',

    'toast.langChanged': 'Idioma actualizado 🌍'
  };

  // STRINGS holds every language. English + Spanish are authored inline above;
  // the remaining dictionaries are injected between the markers below from
  // scripts/i18n-langs.json by `node scripts/gen-i18n.mjs` (regenerate after
  // editing that JSON). They MUST be assigned before boot()/apply() runs so a
  // returning user whose saved language isn't en/es is translated at first paint.
  var STRINGS = { en: EN, es: ES };
  /* <LANGS> */
  STRINGS["pt"] = {"nav.play":"Jogar","nav.puzzles":"Problemas","nav.trophies":"Troféus","nav.rankings":"Classificações","nav.profile":"Perfil","auth.tagline":"Jogue contra o computador, resolva problemas diários, crie sequências e ganhe troféus.","auth.playNow":"▶ Jogar agora","auth.playNowHint":"Não é preciso cadastro — comece uma partida contra o computador com um toque. Crie uma conta para jogar com pessoas reais online.","auth.tabSignIn":"Entrar","auth.tabCreate":"Criar conta","auth.emailOrUsername":"E-mail ou nome de usuário","auth.password":"Senha","auth.signInBtn":"Entrar","auth.forgotPassword":"Esqueceu a senha?","auth.username":"Nome de usuário","auth.email":"E-mail","auth.regionLabel":"Região (cidade, país)","auth.optionalDash":"— opcional","auth.regionPlaceholder":"Opcional — ex.: Austin, EUA","auth.skillLabel":"Nível de habilidade (define seu rating inicial)","auth.skillNew":"Novo no xadrez – 400","auth.skillBeginner":"Iniciante – 800","auth.skillIntermediate":"Intermediário – 1200","auth.skillAdvanced":"Avançado – 1600","auth.eloHelp":"ELO é o seu rating de xadrez — quanto maior, mais forte. Novos jogadores costumam começar entre 400–800. Você pode deixar em branco — usamos Iniciante por padrão.","auth.createBtn":"Criar conta","auth.languageLabel":"Idioma","auth.or":"ou","auth.continueGuest":"Continuar como convidado","auth.guestHint":"Sem cadastro. Seu progresso é salvo neste dispositivo — crie uma conta para mantê-lo em todos os dispositivos.","auth.crossDevice":"Sua conta é armazenada com segurança em nossos servidores, então seu rating e troféus acompanham você em todos os dispositivos. Os nomes de usuário são únicos em todas as plataformas.","settings.title":"Configurações","settings.appearance":"🎨 Aparência","settings.boardTheme":"Tema do tabuleiro","settings.pieceStyle":"Estilo das peças","settings.language":"🌍 Idioma","settings.languageHint":"Escolha seu idioma. O chat com jogadores em outros idiomas continua funcionando — o nome da marca playchesstrophies.com permanece sempre em inglês.","settings.profile":"👤 Perfil","settings.changePic":"🖼️  Alterar foto de perfil","settings.viewProfile":"✏️  Ver meu perfil","settings.notifications":"🔔 Notificações","settings.gameSounds":"Sons do jogo","settings.account":"⚙️ Conta","settings.themeSavedNote":"Seu tema e idioma são salvos no seu perfil — eles permanecem iguais sempre que você entrar.","settings.changePassword":"🔑  Alterar senha","settings.signOut":"Sair","toast.langChanged":"Idioma atualizado 🌍"};
  STRINGS["fr"] = {"nav.play":"Jouer","nav.puzzles":"Énigmes","nav.trophies":"Trophées","nav.rankings":"Classements","nav.profile":"Profil","auth.tagline":"Affrontez l'ordinateur, résolvez des énigmes quotidiennes, enchaînez les séries et gagnez des trophées.","auth.playNow":"▶ Jouer maintenant","auth.playNowHint":"Aucune inscription requise — lancez une partie contre l'ordinateur en un seul geste. Créez un compte pour affronter de vraies personnes en ligne.","auth.tabSignIn":"Se connecter","auth.tabCreate":"Créer un compte","auth.emailOrUsername":"E-mail ou nom d'utilisateur","auth.password":"Mot de passe","auth.signInBtn":"Se connecter","auth.forgotPassword":"Mot de passe oublié ?","auth.username":"Nom d'utilisateur","auth.email":"E-mail","auth.regionLabel":"Région (ville, pays)","auth.optionalDash":"— facultatif","auth.regionPlaceholder":"Facultatif — ex. Austin, États-Unis","auth.skillLabel":"Niveau (définit votre classement de départ)","auth.skillNew":"Débutant total – 400","auth.skillBeginner":"Débutant – 800","auth.skillIntermediate":"Intermédiaire – 1200","auth.skillAdvanced":"Avancé – 1600","auth.eloHelp":"L'ELO est votre classement aux échecs — plus il est élevé, plus vous êtes fort. Les nouveaux joueurs commencent généralement entre 400–800. Vous pouvez laisser vide — Débutant est appliqué par défaut.","auth.createBtn":"Créer un compte","auth.languageLabel":"Langue","auth.or":"ou","auth.continueGuest":"Continuer en tant qu'invité","auth.guestHint":"Aucune inscription. Votre progression est enregistrée sur cet appareil — créez un compte pour la conserver sur tous vos appareils.","auth.crossDevice":"Votre compte est stocké en toute sécurité sur nos serveurs : votre classement et vos trophées vous suivent sur tous vos appareils. Les noms d'utilisateur sont uniques sur toutes les plateformes.","settings.title":"Paramètres","settings.appearance":"🎨 Apparence","settings.boardTheme":"Thème de l'échiquier","settings.pieceStyle":"Style des pièces","settings.language":"🌍 Langue","settings.languageHint":"Choisissez votre langue. Le chat avec des joueurs dans d'autres langues fonctionne toujours — le nom de marque playchesstrophies.com reste toujours en anglais.","settings.profile":"👤 Profil","settings.changePic":"🖼️  Changer la photo de profil","settings.viewProfile":"✏️  Voir mon profil","settings.notifications":"🔔 Notifications","settings.gameSounds":"Sons du jeu","settings.account":"⚙️ Compte","settings.themeSavedNote":"Votre thème et votre langue sont enregistrés dans votre profil — ils restent identiques à chaque connexion.","settings.changePassword":"🔑  Changer le mot de passe","settings.signOut":"Se déconnecter","toast.langChanged":"Langue mise à jour 🌍"};
  STRINGS["de"] = {"nav.play":"Spielen","nav.puzzles":"Rätsel","nav.trophies":"Trophäen","nav.rankings":"Ranglisten","nav.profile":"Profil","auth.tagline":"Spiele gegen den Computer, löse tägliche Rätsel, baue Serien auf und verdiene Trophäen.","auth.playNow":"▶ Jetzt spielen","auth.playNowHint":"Keine Anmeldung nötig — starte mit einem Tippen eine Partie gegen den Computer. Erstelle ein Konto, um online gegen echte Menschen zu spielen.","auth.tabSignIn":"Anmelden","auth.tabCreate":"Konto erstellen","auth.emailOrUsername":"E-Mail oder Benutzername","auth.password":"Passwort","auth.signInBtn":"Anmelden","auth.forgotPassword":"Passwort vergessen?","auth.username":"Benutzername","auth.email":"E-Mail","auth.regionLabel":"Region (Stadt, Land)","auth.optionalDash":"— optional","auth.regionPlaceholder":"Optional — z. B. Austin, USA","auth.skillLabel":"Spielstärke (legt deine Startwertung fest)","auth.skillNew":"Neu im Schach – 400","auth.skillBeginner":"Anfänger – 800","auth.skillIntermediate":"Fortgeschritten – 1200","auth.skillAdvanced":"Erfahren – 1600","auth.eloHelp":"ELO ist deine Schachwertung — höher bedeutet stärker. Neue Spieler starten meist zwischen 400–800. Du kannst das Feld leer lassen — wir verwenden standardmäßig Anfänger.","auth.createBtn":"Konto erstellen","auth.languageLabel":"Sprache","auth.or":"oder","auth.continueGuest":"Als Gast fortfahren","auth.guestHint":"Keine Anmeldung. Dein Fortschritt wird auf diesem Gerät gespeichert — erstelle ein Konto, um ihn auf allen Geräten zu behalten.","auth.crossDevice":"Dein Konto wird sicher auf unseren Servern gespeichert, sodass dir deine Wertung und Trophäen auf allen Geräten folgen. Benutzernamen sind plattformübergreifend einzigartig.","settings.title":"Einstellungen","settings.appearance":"🎨 Darstellung","settings.boardTheme":"Brett-Design","settings.pieceStyle":"Figurenstil","settings.language":"🌍 Sprache","settings.languageHint":"Wähle deine Sprache. Der Chat mit Spielern in anderen Sprachen funktioniert weiterhin — der Markenname playchesstrophies.com bleibt immer auf Englisch.","settings.profile":"👤 Profil","settings.changePic":"🖼️  Profilbild ändern","settings.viewProfile":"✏️  Mein Profil ansehen","settings.notifications":"🔔 Benachrichtigungen","settings.gameSounds":"Spielgeräusche","settings.account":"⚙️ Konto","settings.themeSavedNote":"Dein Design und deine Sprache werden in deinem Profil gespeichert — sie bleiben bei jeder Anmeldung gleich.","settings.changePassword":"🔑  Passwort ändern","settings.signOut":"Abmelden","toast.langChanged":"Sprache aktualisiert 🌍"};
  STRINGS["it"] = {"nav.play":"Gioca","nav.puzzles":"Rompicapi","nav.trophies":"Trofei","nav.rankings":"Classifiche","nav.profile":"Profilo","auth.tagline":"Gioca contro il computer, risolvi rompicapi giornalieri, crea serie e conquista trofei.","auth.playNow":"▶ Gioca ora","auth.playNowHint":"Nessuna registrazione necessaria — inizia una partita contro il computer con un tocco. Crea un account per giocare con persone reali online.","auth.tabSignIn":"Accedi","auth.tabCreate":"Crea account","auth.emailOrUsername":"E-mail o nome utente","auth.password":"Password","auth.signInBtn":"Accedi","auth.forgotPassword":"Password dimenticata?","auth.username":"Nome utente","auth.email":"E-mail","auth.regionLabel":"Regione (città, paese)","auth.optionalDash":"— facoltativo","auth.regionPlaceholder":"Facoltativo — es. Austin, USA","auth.skillLabel":"Livello (imposta il tuo punteggio iniziale)","auth.skillNew":"Nuovo agli scacchi – 400","auth.skillBeginner":"Principiante – 800","auth.skillIntermediate":"Intermedio – 1200","auth.skillAdvanced":"Avanzato – 1600","auth.eloHelp":"L'ELO è il tuo punteggio agli scacchi — più alto significa più forte. I nuovi giocatori di solito iniziano tra 400–800. Puoi lasciarlo vuoto — per impostazione predefinita usiamo Principiante.","auth.createBtn":"Crea account","auth.languageLabel":"Lingua","auth.or":"o","auth.continueGuest":"Continua come ospite","auth.guestHint":"Nessuna registrazione. I tuoi progressi vengono salvati su questo dispositivo — crea un account per mantenerli su tutti i dispositivi.","auth.crossDevice":"Il tuo account è archiviato in modo sicuro sui nostri server, così il tuo punteggio e i tuoi trofei ti seguono su tutti i dispositivi. I nomi utente sono unici su ogni piattaforma.","settings.title":"Impostazioni","settings.appearance":"🎨 Aspetto","settings.boardTheme":"Tema della scacchiera","settings.pieceStyle":"Stile dei pezzi","settings.language":"🌍 Lingua","settings.languageHint":"Scegli la tua lingua. La chat con giocatori in altre lingue continua a funzionare — il nome del marchio playchesstrophies.com resta sempre in inglese.","settings.profile":"👤 Profilo","settings.changePic":"🖼️  Cambia foto del profilo","settings.viewProfile":"✏️  Visualizza il mio profilo","settings.notifications":"🔔 Notifiche","settings.gameSounds":"Suoni di gioco","settings.account":"⚙️ Account","settings.themeSavedNote":"Il tuo tema e la tua lingua vengono salvati nel tuo profilo — restano invariati a ogni accesso.","settings.changePassword":"🔑  Cambia password","settings.signOut":"Esci","toast.langChanged":"Lingua aggiornata 🌍"};
  STRINGS["ru"] = {"nav.play":"Играть","nav.puzzles":"Задачи","nav.trophies":"Трофеи","nav.rankings":"Рейтинг","nav.profile":"Профиль","auth.tagline":"Играйте с компьютером, решайте ежедневные задачи, копите серии, зарабатывайте трофеи.","auth.playNow":"▶ Играть сейчас","auth.playNowHint":"Регистрация не нужна — начните партию с компьютером в одно касание. Создайте аккаунт, чтобы играть с реальными людьми онлайн.","auth.tabSignIn":"Вход","auth.tabCreate":"Создать аккаунт","auth.emailOrUsername":"Эл. почта или имя пользователя","auth.password":"Пароль","auth.signInBtn":"Войти","auth.forgotPassword":"Забыли пароль?","auth.username":"Имя пользователя","auth.email":"Эл. почта","auth.regionLabel":"Регион (город, страна)","auth.optionalDash":"— необязательно","auth.regionPlaceholder":"Необязательно — напр. Остин, США","auth.skillLabel":"Уровень игры (задаёт стартовый рейтинг)","auth.skillNew":"Новичок в шахматах – 400","auth.skillBeginner":"Начинающий – 800","auth.skillIntermediate":"Средний – 1200","auth.skillAdvanced":"Продвинутый – 1600","auth.eloHelp":"ELO — это ваш шахматный рейтинг: выше значит сильнее. Новички обычно начинают с 400–800. Можно оставить пустым — по умолчанию будет «Начинающий».","auth.createBtn":"Создать аккаунт","auth.languageLabel":"Язык","auth.or":"или","auth.continueGuest":"Продолжить как гость","auth.guestHint":"Без регистрации. Ваш прогресс сохраняется на этом устройстве — создайте аккаунт, чтобы сохранить его на всех устройствах.","auth.crossDevice":"Ваш аккаунт надёжно хранится на наших серверах, поэтому рейтинг и трофеи доступны на всех устройствах. Имена пользователей уникальны на всех платформах.","settings.title":"Настройки","settings.appearance":"🎨 Внешний вид","settings.boardTheme":"Тема доски","settings.pieceStyle":"Стиль фигур","settings.language":"🌍 Язык","settings.languageHint":"Выберите язык. Чат с игроками на других языках по-прежнему работает — название бренда playchesstrophies.com всегда остаётся на английском.","settings.profile":"👤 Профиль","settings.changePic":"🖼️  Сменить фото профиля","settings.viewProfile":"✏️  Мой профиль","settings.notifications":"🔔 Уведомления","settings.gameSounds":"Звуки игры","settings.account":"⚙️ Аккаунт","settings.themeSavedNote":"Ваша тема и язык сохраняются в профиле — они остаются неизменными при каждом входе.","settings.changePassword":"🔑  Сменить пароль","settings.signOut":"Выйти","toast.langChanged":"Язык обновлён 🌍"};
  STRINGS["zh"] = {"nav.play":"对弈","nav.puzzles":"残局","nav.trophies":"奖杯","nav.rankings":"排行榜","nav.profile":"个人资料","auth.tagline":"与电脑对弈，每日解谜，连胜不断，赢取奖杯。","auth.playNow":"▶ 立即开始","auth.playNowHint":"无需注册——一键即可与电脑开局。创建账号即可与真人在线对弈。","auth.tabSignIn":"登录","auth.tabCreate":"创建账号","auth.emailOrUsername":"邮箱或用户名","auth.password":"密码","auth.signInBtn":"登录","auth.forgotPassword":"忘记密码？","auth.username":"用户名","auth.email":"邮箱","auth.regionLabel":"地区（城市、国家）","auth.optionalDash":"— 选填","auth.regionPlaceholder":"选填——例如 奥斯汀，美国","auth.skillLabel":"棋力水平（决定你的初始评分）","auth.skillNew":"国际象棋新手 – 400","auth.skillBeginner":"初级 – 800","auth.skillIntermediate":"中级 – 1200","auth.skillAdvanced":"高级 – 1600","auth.eloHelp":"ELO 是你的国际象棋评分——越高越强。新手通常从 400–800 起步。可以留空——默认设为初级。","auth.createBtn":"创建账号","auth.languageLabel":"语言","auth.or":"或","auth.continueGuest":"以访客身份继续","auth.guestHint":"无需注册。你的进度保存在本设备——创建账号即可跨设备保留。","auth.crossDevice":"你的账号安全存储在我们的服务器上，因此评分和奖杯可跨设备同步。用户名在所有平台上均唯一。","settings.title":"设置","settings.appearance":"🎨 外观","settings.boardTheme":"棋盘主题","settings.pieceStyle":"棋子样式","settings.language":"🌍 语言","settings.languageHint":"选择你的语言。与其他语言的玩家聊天仍然可用——playchesstrophies.com 品牌名称始终保持英文。","settings.profile":"👤 个人资料","settings.changePic":"🖼️  更换头像","settings.viewProfile":"✏️  查看我的资料","settings.notifications":"🔔 通知","settings.gameSounds":"游戏音效","settings.account":"⚙️ 账号","settings.themeSavedNote":"你的主题和语言已保存到个人资料——每次登录都保持不变。","settings.changePassword":"🔑  修改密码","settings.signOut":"退出登录","toast.langChanged":"语言已更新 🌍"};
  STRINGS["ja"] = {"nav.play":"対局","nav.puzzles":"パズル","nav.trophies":"トロフィー","nav.rankings":"ランキング","nav.profile":"プロフィール","auth.tagline":"コンピューターと対局し、デイリーパズルを解き、連続記録を伸ばして、トロフィーを獲得しよう。","auth.playNow":"▶ いますぐプレイ","auth.playNowHint":"登録不要——ワンタップでコンピューターとの対局を開始。アカウントを作成すれば、オンラインで実際のプレイヤーと対戦できます。","auth.tabSignIn":"ログイン","auth.tabCreate":"アカウント作成","auth.emailOrUsername":"メールアドレスまたはユーザー名","auth.password":"パスワード","auth.signInBtn":"ログイン","auth.forgotPassword":"パスワードをお忘れですか？","auth.username":"ユーザー名","auth.email":"メールアドレス","auth.regionLabel":"地域（市区、国）","auth.optionalDash":"— 任意","auth.regionPlaceholder":"任意——例：オースティン、アメリカ","auth.skillLabel":"棋力レベル（開始レーティングを設定）","auth.skillNew":"チェス初心者 – 400","auth.skillBeginner":"ビギナー – 800","auth.skillIntermediate":"中級 – 1200","auth.skillAdvanced":"上級 – 1600","auth.eloHelp":"ELO はあなたのチェスレーティングです——高いほど強さを示します。初心者は通常 400–800 から始めます。空欄のままでも構いません——初期値はビギナーです。","auth.createBtn":"アカウント作成","auth.languageLabel":"言語","auth.or":"または","auth.continueGuest":"ゲストとして続ける","auth.guestHint":"登録不要。進行状況はこの端末に保存されます——アカウントを作成すれば、複数の端末で引き継げます。","auth.crossDevice":"アカウントは当社のサーバーに安全に保存されるため、レーティングとトロフィーは複数の端末で引き継がれます。ユーザー名はすべてのプラットフォームで一意です。","settings.title":"設定","settings.appearance":"🎨 外観","settings.boardTheme":"ボードテーマ","settings.pieceStyle":"駒のスタイル","settings.language":"🌍 言語","settings.languageHint":"言語を選択してください。他の言語のプレイヤーとのチャットも引き続き使えます——playchesstrophies.com のブランド名は常に英語のままです。","settings.profile":"👤 プロフィール","settings.changePic":"🖼️  プロフィール画像を変更","settings.viewProfile":"✏️  プロフィールを表示","settings.notifications":"🔔 通知","settings.gameSounds":"ゲームサウンド","settings.account":"⚙️ アカウント","settings.themeSavedNote":"テーマと言語はプロフィールに保存されます——ログインするたびに同じ設定が維持されます。","settings.changePassword":"🔑  パスワードを変更","settings.signOut":"ログアウト","toast.langChanged":"言語を更新しました 🌍"};
  STRINGS["id"] = {"nav.play":"Main","nav.puzzles":"Teka-teki","nav.trophies":"Trofi","nav.rankings":"Peringkat","nav.profile":"Profil","auth.tagline":"Main lawan komputer, pecahkan teka-teki harian, bangun rentetan, raih trofi.","auth.playNow":"▶ Main sekarang","auth.playNowHint":"Tanpa pendaftaran — mulai permainan lawan komputer dengan sekali ketuk. Buat akun untuk bermain dengan orang sungguhan secara online.","auth.tabSignIn":"Masuk","auth.tabCreate":"Buat akun","auth.emailOrUsername":"Email atau nama pengguna","auth.password":"Kata sandi","auth.signInBtn":"Masuk","auth.forgotPassword":"Lupa kata sandi?","auth.username":"Nama pengguna","auth.email":"Email","auth.regionLabel":"Wilayah (kota, negara)","auth.optionalDash":"— opsional","auth.regionPlaceholder":"Opsional — mis. Austin, Amerika Serikat","auth.skillLabel":"Tingkat keterampilan (menentukan rating awal Anda)","auth.skillNew":"Baru main catur – 400","auth.skillBeginner":"Pemula – 800","auth.skillIntermediate":"Menengah – 1200","auth.skillAdvanced":"Mahir – 1600","auth.eloHelp":"ELO adalah rating catur Anda — makin tinggi makin kuat. Pemain baru biasanya mulai sekitar 400–800. Bisa dikosongkan — defaultnya Pemula.","auth.createBtn":"Buat akun","auth.languageLabel":"Bahasa","auth.or":"atau","auth.continueGuest":"Lanjut sebagai tamu","auth.guestHint":"Tanpa pendaftaran. Progres Anda tersimpan di perangkat ini — buat akun untuk menyimpannya di semua perangkat.","auth.crossDevice":"Akun Anda tersimpan aman di server kami, jadi rating dan trofi Anda mengikuti di semua perangkat. Nama pengguna bersifat unik di setiap platform.","settings.title":"Pengaturan","settings.appearance":"🎨 Tampilan","settings.boardTheme":"Tema Papan","settings.pieceStyle":"Gaya Bidak","settings.language":"🌍 Bahasa","settings.languageHint":"Pilih bahasa Anda. Mengobrol dengan pemain dalam bahasa lain tetap berfungsi — nama merek playchesstrophies.com selalu tetap dalam bahasa Inggris.","settings.profile":"👤 Profil","settings.changePic":"🖼️  Ubah Foto Profil","settings.viewProfile":"✏️  Lihat Profil Saya","settings.notifications":"🔔 Notifikasi","settings.gameSounds":"Suara permainan","settings.account":"⚙️ Akun","settings.themeSavedNote":"Tema dan bahasa Anda tersimpan di profil — keduanya tetap sama setiap kali Anda masuk.","settings.changePassword":"🔑  Ubah Kata Sandi","settings.signOut":"Keluar","toast.langChanged":"Bahasa diperbarui 🌍"};
  STRINGS["tl"] = {"nav.play":"Maglaro","nav.puzzles":"Mga Palaisipan","nav.trophies":"Mga Tropeo","nav.rankings":"Ranggo","nav.profile":"Profile","auth.tagline":"Makipaglaro sa kompyuter, lutasin ang pang-araw-araw na palaisipan, magtipon ng streak, at magkamit ng tropeo.","auth.playNow":"▶ Maglaro na","auth.playNowHint":"Hindi kailangan mag-sign up — magsimula ng laro vs kompyuter sa isang tap. Gumawa ng account para makipaglaro sa totoong tao online.","auth.tabSignIn":"Mag-sign in","auth.tabCreate":"Gumawa ng account","auth.emailOrUsername":"Email o username","auth.password":"Password","auth.signInBtn":"Mag-sign in","auth.forgotPassword":"Nakalimutan ang password?","auth.username":"Username","auth.email":"Email","auth.regionLabel":"Rehiyon (lungsod, bansa)","auth.optionalDash":"— opsyonal","auth.regionPlaceholder":"Opsyonal — hal. Austin, USA","auth.skillLabel":"Antas ng kasanayan (nagtatakda ng iyong panimulang rating)","auth.skillNew":"Baguhan sa chess – 400","auth.skillBeginner":"Nagsisimula – 800","auth.skillIntermediate":"Intermedyo – 1200","auth.skillAdvanced":"Advanced – 1600","auth.eloHelp":"Ang ELO ang iyong rating sa chess — mas mataas, mas malakas. Ang mga bagong manlalaro ay karaniwang nagsisimula sa mga 400–800. Maaari mo itong iwanan — Beginner ang default namin.","auth.createBtn":"Gumawa ng account","auth.languageLabel":"Wika","auth.or":"o","auth.continueGuest":"Magpatuloy bilang guest","auth.guestHint":"Walang sign-up. Naka-save ang iyong progreso sa device na ito — gumawa ng account para mapanatili ito sa iba't ibang device.","auth.crossDevice":"Ligtas na nakaimbak ang iyong account sa aming mga server, kaya kasama mo ang iyong rating at mga tropeo sa iba't ibang device. Natatangi ang mga username sa bawat platform.","settings.title":"Mga Setting","settings.appearance":"🎨 Hitsura","settings.boardTheme":"Tema ng Board","settings.pieceStyle":"Estilo ng Piyesa","settings.language":"🌍 Wika","settings.languageHint":"Piliin ang iyong wika. Gumagana pa rin ang pakikipag-chat sa ibang wika — ang brand name na playchesstrophies.com ay laging nananatiling Ingles.","settings.profile":"👤 Profile","settings.changePic":"🖼️  Palitan ang Profile Picture","settings.viewProfile":"✏️  Tingnan ang Aking Profile","settings.notifications":"🔔 Mga Notification","settings.gameSounds":"Mga tunog ng laro","settings.account":"⚙️ Account","settings.themeSavedNote":"Naka-save sa iyong profile ang iyong tema at wika — nananatili itong pareho sa tuwing mag-sign in ka.","settings.changePassword":"🔑  Palitan ang Password","settings.signOut":"Mag-sign Out","toast.langChanged":"Na-update ang wika 🌍"};
  STRINGS["hi"] = {"nav.play":"खेलें","nav.puzzles":"पहेलियाँ","nav.trophies":"ट्रॉफियाँ","nav.rankings":"रैंकिंग","nav.profile":"प्रोफ़ाइल","auth.tagline":"कंप्यूटर से खेलें, रोज़ाना पहेलियाँ हल करें, स्ट्रीक बनाएँ, ट्रॉफियाँ जीतें।","auth.playNow":"▶ अभी खेलें","auth.playNowHint":"साइन-अप की ज़रूरत नहीं — एक टैप में कंप्यूटर के विरुद्ध खेल शुरू करें। ऑनलाइन असली लोगों से खेलने के लिए खाता बनाएँ।","auth.tabSignIn":"साइन इन करें","auth.tabCreate":"खाता बनाएँ","auth.emailOrUsername":"ईमेल या यूज़रनेम","auth.password":"पासवर्ड","auth.signInBtn":"साइन इन करें","auth.forgotPassword":"पासवर्ड भूल गए?","auth.username":"यूज़रनेम","auth.email":"ईमेल","auth.regionLabel":"क्षेत्र (शहर, देश)","auth.optionalDash":"— वैकल्पिक","auth.regionPlaceholder":"वैकल्पिक — जैसे ऑस्टिन, अमेरिका","auth.skillLabel":"कौशल स्तर (आपकी शुरुआती रेटिंग तय करता है)","auth.skillNew":"शतरंज में नए – 400","auth.skillBeginner":"शुरुआती – 800","auth.skillIntermediate":"मध्यम – 1200","auth.skillAdvanced":"उन्नत – 1600","auth.eloHelp":"ELO आपकी शतरंज रेटिंग है — जितनी ज़्यादा, उतने मज़बूत। नए खिलाड़ी आमतौर पर 400–800 के आसपास से शुरू करते हैं। आप इसे छोड़ सकते हैं — हमारा डिफ़ॉल्ट Beginner है।","auth.createBtn":"खाता बनाएँ","auth.languageLabel":"भाषा","auth.or":"या","auth.continueGuest":"अतिथि के रूप में जारी रखें","auth.guestHint":"कोई साइन-अप नहीं। आपकी प्रगति इस डिवाइस पर सहेजी जाती है — इसे सभी डिवाइस पर रखने के लिए खाता बनाएँ।","auth.crossDevice":"आपका खाता हमारे सर्वर पर सुरक्षित रूप से संग्रहीत है, इसलिए आपकी रेटिंग और ट्रॉफियाँ हर डिवाइस पर आपके साथ चलती हैं। यूज़रनेम हर प्लेटफ़ॉर्म पर अद्वितीय होते हैं।","settings.title":"सेटिंग्स","settings.appearance":"🎨 रूप","settings.boardTheme":"बोर्ड थीम","settings.pieceStyle":"मोहरे की शैली","settings.language":"🌍 भाषा","settings.languageHint":"अपनी भाषा चुनें। अन्य भाषाओं में खिलाड़ियों से चैट अब भी काम करती है — playchesstrophies.com ब्रांड नाम हमेशा अंग्रेज़ी में ही रहता है।","settings.profile":"👤 प्रोफ़ाइल","settings.changePic":"🖼️  प्रोफ़ाइल चित्र बदलें","settings.viewProfile":"✏️  मेरी प्रोफ़ाइल देखें","settings.notifications":"🔔 सूचनाएँ","settings.gameSounds":"खेल की ध्वनियाँ","settings.account":"⚙️ खाता","settings.themeSavedNote":"आपकी थीम और भाषा आपकी प्रोफ़ाइल में सहेजी जाती हैं — हर बार साइन इन करने पर ये वही रहती हैं।","settings.changePassword":"🔑  पासवर्ड बदलें","settings.signOut":"साइन आउट करें","toast.langChanged":"भाषा अपडेट हो गई 🌍"};
  STRINGS["bn"] = {"nav.play":"খেলুন","nav.puzzles":"ধাঁধা","nav.trophies":"ট্রফি","nav.rankings":"র‍্যাঙ্কিং","nav.profile":"প্রোফাইল","auth.tagline":"কম্পিউটারের সাথে খেলুন, প্রতিদিনের ধাঁধা সমাধান করুন, স্ট্রিক গড়ুন, ট্রফি জিতুন।","auth.playNow":"▶ এখনই খেলুন","auth.playNowHint":"সাইন-আপের প্রয়োজন নেই — এক ট্যাপে কম্পিউটারের বিরুদ্ধে খেলা শুরু করুন। অনলাইনে আসল মানুষের সাথে খেলতে একটি অ্যাকাউন্ট তৈরি করুন।","auth.tabSignIn":"সাইন ইন করুন","auth.tabCreate":"অ্যাকাউন্ট তৈরি করুন","auth.emailOrUsername":"ইমেল বা ইউজারনেম","auth.password":"পাসওয়ার্ড","auth.signInBtn":"সাইন ইন করুন","auth.forgotPassword":"পাসওয়ার্ড ভুলে গেছেন?","auth.username":"ইউজারনেম","auth.email":"ইমেল","auth.regionLabel":"অঞ্চল (শহর, দেশ)","auth.optionalDash":"— ঐচ্ছিক","auth.regionPlaceholder":"ঐচ্ছিক — যেমন অস্টিন, আমেরিকা","auth.skillLabel":"দক্ষতার স্তর (আপনার শুরুর রেটিং নির্ধারণ করে)","auth.skillNew":"দাবায় নতুন – 400","auth.skillBeginner":"শিক্ষানবিশ – 800","auth.skillIntermediate":"মধ্যম – 1200","auth.skillAdvanced":"উন্নত – 1600","auth.eloHelp":"ELO হলো আপনার দাবার রেটিং — যত বেশি, তত শক্তিশালী। নতুন খেলোয়াড়রা সাধারণত 400–800 এর কাছাকাছি থেকে শুরু করেন। আপনি এটি খালি রাখতে পারেন — আমাদের ডিফল্ট Beginner।","auth.createBtn":"অ্যাকাউন্ট তৈরি করুন","auth.languageLabel":"ভাষা","auth.or":"অথবা","auth.continueGuest":"অতিথি হিসেবে চালিয়ে যান","auth.guestHint":"কোনো সাইন-আপ নেই। আপনার অগ্রগতি এই ডিভাইসে সংরক্ষিত হয় — সব ডিভাইসে রাখতে একটি অ্যাকাউন্ট তৈরি করুন।","auth.crossDevice":"আপনার অ্যাকাউন্ট আমাদের সার্ভারে নিরাপদে সংরক্ষিত থাকে, তাই আপনার রেটিং ও ট্রফি প্রতিটি ডিভাইসে আপনার সাথে থাকে। ইউজারনেম প্রতিটি প্ল্যাটফর্মে অনন্য।","settings.title":"সেটিংস","settings.appearance":"🎨 অবয়ব","settings.boardTheme":"বোর্ড থিম","settings.pieceStyle":"ঘুঁটির স্টাইল","settings.language":"🌍 ভাষা","settings.languageHint":"আপনার ভাষা বেছে নিন। অন্য ভাষার খেলোয়াড়দের সাথে চ্যাট এখনও কাজ করে — playchesstrophies.com ব্র্যান্ড নাম সবসময় ইংরেজিতেই থাকে।","settings.profile":"👤 প্রোফাইল","settings.changePic":"🖼️  প্রোফাইল ছবি পরিবর্তন করুন","settings.viewProfile":"✏️  আমার প্রোফাইল দেখুন","settings.notifications":"🔔 বিজ্ঞপ্তি","settings.gameSounds":"খেলার শব্দ","settings.account":"⚙️ অ্যাকাউন্ট","settings.themeSavedNote":"আপনার থিম ও ভাষা আপনার প্রোফাইলে সংরক্ষিত থাকে — প্রতিবার সাইন ইন করলে এগুলো একই থাকে।","settings.changePassword":"🔑  পাসওয়ার্ড পরিবর্তন করুন","settings.signOut":"সাইন আউট করুন","toast.langChanged":"ভাষা আপডেট হয়েছে 🌍"};
  STRINGS["ta"] = {"nav.play":"விளையாடு","nav.puzzles":"புதிர்கள்","nav.trophies":"கிண்ணங்கள்","nav.rankings":"தரவரிசை","nav.profile":"சுயவிவரம்","auth.tagline":"கணினியுடன் விளையாடுங்கள், தினசரி புதிர்களைத் தீர்க்கவும், தொடர்ச்சிகளை உருவாக்கவும், கிண்ணங்களை வெல்லவும்.","auth.playNow":"▶ இப்போது விளையாடு","auth.playNowHint":"பதிவு தேவையில்லை — ஒரே தட்டில் கணினிக்கு எதிராக ஆட்டத்தைத் தொடங்குங்கள். ஆன்லைனில் நிஜ நபர்களுடன் விளையாட கணக்கை உருவாக்குங்கள்.","auth.tabSignIn":"உள்நுழைய","auth.tabCreate":"கணக்கை உருவாக்கு","auth.emailOrUsername":"மின்னஞ்சல் அல்லது பயனர்பெயர்","auth.password":"கடவுச்சொல்","auth.signInBtn":"உள்நுழைய","auth.forgotPassword":"கடவுச்சொல் மறந்துவிட்டதா?","auth.username":"பயனர்பெயர்","auth.email":"மின்னஞ்சல்","auth.regionLabel":"பகுதி (நகரம், நாடு)","auth.optionalDash":"— விருப்பத்திற்குரியது","auth.regionPlaceholder":"விருப்பம் — எ.கா. Austin, அமெரிக்கா","auth.skillLabel":"திறன் நிலை (உங்கள் தொடக்க மதிப்பீட்டை அமைக்கிறது)","auth.skillNew":"சதுரங்கத்திற்குப் புதியவர் – 400","auth.skillBeginner":"ஆரம்பநிலை – 800","auth.skillIntermediate":"இடைநிலை – 1200","auth.skillAdvanced":"மேம்பட்ட நிலை – 1600","auth.eloHelp":"ELO என்பது உங்கள் சதுரங்க மதிப்பீடு — அதிகமானால் வலிமையானது. புதிய வீரர்கள் பொதுவாக 400–800 அளவில் தொடங்குவார்கள். இதை விட்டுவிடலாம் — நாங்கள் இயல்பாக ஆரம்பநிலையை அமைக்கிறோம்.","auth.createBtn":"கணக்கை உருவாக்கு","auth.languageLabel":"மொழி","auth.or":"அல்லது","auth.continueGuest":"விருந்தினராகத் தொடரவும்","auth.guestHint":"பதிவு இல்லை. உங்கள் முன்னேற்றம் இந்தச் சாதனத்தில் சேமிக்கப்படும் — சாதனங்களுக்கிடையே அதை வைத்திருக்க கணக்கை உருவாக்குங்கள்.","auth.crossDevice":"உங்கள் கணக்கு எங்கள் சேவையகங்களில் பாதுகாப்பாகச் சேமிக்கப்படுகிறது, எனவே உங்கள் மதிப்பீடும் கிண்ணங்களும் சாதனங்களுக்கிடையே உங்களைப் பின்தொடரும். பயனர்பெயர்கள் ஒவ்வொரு தளத்திலும் தனித்துவமானவை.","settings.title":"அமைப்புகள்","settings.appearance":"🎨 தோற்றம்","settings.boardTheme":"பலகை தீம்","settings.pieceStyle":"காய் பாணி","settings.language":"🌍 மொழி","settings.languageHint":"உங்கள் மொழியைத் தேர்ந்தெடுக்கவும். பிற மொழிகளில் வீரர்களுடன் அரட்டை அடிப்பது இன்னும் வேலை செய்கிறது — playchesstrophies.com பிராண்ட் பெயர் எப்போதும் ஆங்கிலத்திலேயே இருக்கும்.","settings.profile":"👤 சுயவிவரம்","settings.changePic":"🖼️  சுயவிவரப் படத்தை மாற்று","settings.viewProfile":"✏️  என் சுயவிவரத்தைப் பார்","settings.notifications":"🔔 அறிவிப்புகள்","settings.gameSounds":"ஆட்ட ஒலிகள்","settings.account":"⚙️ கணக்கு","settings.themeSavedNote":"உங்கள் தீம் மற்றும் மொழி உங்கள் சுயவிவரத்தில் சேமிக்கப்படுகின்றன — நீங்கள் உள்நுழையும் ஒவ்வொரு முறையும் அவை அப்படியே இருக்கும்.","settings.changePassword":"🔑  கடவுச்சொல்லை மாற்று","settings.signOut":"வெளியேறு","toast.langChanged":"மொழி புதுப்பிக்கப்பட்டது 🌍"};
  STRINGS["te"] = {"nav.play":"ఆడండి","nav.puzzles":"పజిల్స్","nav.trophies":"ట్రోఫీలు","nav.rankings":"ర్యాంకింగ్‌లు","nav.profile":"ప్రొఫైల్","auth.tagline":"కంప్యూటర్‌తో ఆడండి, రోజువారీ పజిల్స్ పరిష్కరించండి, స్ట్రీక్‌లు నిర్మించండి, ట్రోఫీలు గెలవండి.","auth.playNow":"▶ ఇప్పుడు ఆడండి","auth.playNowHint":"సైన్-అప్ అవసరం లేదు — ఒక్క ట్యాప్‌తో కంప్యూటర్‌తో గేమ్ ప్రారంభించండి. ఆన్‌లైన్‌లో నిజమైన వ్యక్తులతో ఆడటానికి ఖాతాను సృష్టించండి.","auth.tabSignIn":"సైన్ ఇన్","auth.tabCreate":"ఖాతా సృష్టించండి","auth.emailOrUsername":"ఇమెయిల్ లేదా యూజర్‌నేమ్","auth.password":"పాస్‌వర్డ్","auth.signInBtn":"సైన్ ఇన్","auth.forgotPassword":"పాస్‌వర్డ్ మర్చిపోయారా?","auth.username":"యూజర్‌నేమ్","auth.email":"ఇమెయిల్","auth.regionLabel":"ప్రాంతం (నగరం, దేశం)","auth.optionalDash":"— ఐచ్ఛికం","auth.regionPlaceholder":"ఐచ్ఛికం — ఉదా. Austin, USA","auth.skillLabel":"నైపుణ్య స్థాయి (మీ ప్రారంభ రేటింగ్‌ను సెట్ చేస్తుంది)","auth.skillNew":"చెస్‌కు కొత్తవారు – 400","auth.skillBeginner":"ప్రారంభకుడు – 800","auth.skillIntermediate":"మధ్యస్థం – 1200","auth.skillAdvanced":"ఆధునిక – 1600","auth.eloHelp":"ELO అనేది మీ చెస్ రేటింగ్ — ఎక్కువ ఉంటే బలమైనది. కొత్త ఆటగాళ్లు సాధారణంగా 400–800 చుట్టూ ప్రారంభిస్తారు. దీన్ని వదిలేయవచ్చు — మేము డిఫాల్ట్‌గా ప్రారంభకుడిని సెట్ చేస్తాము.","auth.createBtn":"ఖాతా సృష్టించండి","auth.languageLabel":"భాష","auth.or":"లేదా","auth.continueGuest":"అతిథిగా కొనసాగండి","auth.guestHint":"సైన్-అప్ లేదు. మీ పురోగతి ఈ పరికరంలో సేవ్ అవుతుంది — పరికరాల మధ్య దాన్ని ఉంచుకోవడానికి ఖాతాను సృష్టించండి.","auth.crossDevice":"మీ ఖాతా మా సర్వర్‌లలో సురక్షితంగా నిల్వ చేయబడుతుంది, కాబట్టి మీ రేటింగ్ మరియు ట్రోఫీలు పరికరాల మధ్య మిమ్మల్ని అనుసరిస్తాయి. యూజర్‌నేమ్‌లు ప్రతి ప్లాట్‌ఫారమ్‌లో ప్రత్యేకమైనవి.","settings.title":"సెట్టింగ్‌లు","settings.appearance":"🎨 రూపం","settings.boardTheme":"బోర్డు థీమ్","settings.pieceStyle":"పావు శైలి","settings.language":"🌍 భాష","settings.languageHint":"మీ భాషను ఎంచుకోండి. ఇతర భాషల్లో ఆటగాళ్లతో చాట్ చేయడం ఇప్పటికీ పనిచేస్తుంది — playchesstrophies.com బ్రాండ్ పేరు ఎల్లప్పుడూ ఇంగ్లీష్‌లోనే ఉంటుంది.","settings.profile":"👤 ప్రొఫైల్","settings.changePic":"🖼️  ప్రొఫైల్ చిత్రాన్ని మార్చండి","settings.viewProfile":"✏️  నా ప్రొఫైల్ చూడండి","settings.notifications":"🔔 నోటిఫికేషన్‌లు","settings.gameSounds":"గేమ్ ధ్వనులు","settings.account":"⚙️ ఖాతా","settings.themeSavedNote":"మీ థీమ్ మరియు భాష మీ ప్రొఫైల్‌లో సేవ్ చేయబడతాయి — మీరు సైన్ ఇన్ చేసిన ప్రతిసారీ అవి అలాగే ఉంటాయి.","settings.changePassword":"🔑  పాస్‌వర్డ్ మార్చండి","settings.signOut":"సైన్ అవుట్","toast.langChanged":"భాష నవీకరించబడింది 🌍"};
  STRINGS["kn"] = {"nav.play":"ಆಡಿ","nav.puzzles":"ಒಗಟುಗಳು","nav.trophies":"ಟ್ರೋಫಿಗಳು","nav.rankings":"ಶ್ರೇಯಾಂಕಗಳು","nav.profile":"ಪ್ರೊಫೈಲ್","auth.tagline":"ಕಂಪ್ಯೂಟರ್‌ನೊಂದಿಗೆ ಆಡಿ, ದೈನಂದಿನ ಒಗಟುಗಳನ್ನು ಪರಿಹರಿಸಿ, ಸ್ಟ್ರೀಕ್‌ಗಳನ್ನು ನಿರ್ಮಿಸಿ, ಟ್ರೋಫಿಗಳನ್ನು ಗೆಲ್ಲಿ.","auth.playNow":"▶ ಈಗ ಆಡಿ","auth.playNowHint":"ಸೈನ್-ಅಪ್ ಅಗತ್ಯವಿಲ್ಲ — ಒಂದೇ ಟ್ಯಾಪ್‌ನಲ್ಲಿ ಕಂಪ್ಯೂಟರ್ ವಿರುದ್ಧ ಆಟ ಪ್ರಾರಂಭಿಸಿ. ಆನ್‌ಲೈನ್‌ನಲ್ಲಿ ನಿಜವಾದ ಜನರೊಂದಿಗೆ ಆಡಲು ಖಾತೆ ರಚಿಸಿ.","auth.tabSignIn":"ಸೈನ್ ಇನ್","auth.tabCreate":"ಖಾತೆ ರಚಿಸಿ","auth.emailOrUsername":"ಇಮೇಲ್ ಅಥವಾ ಬಳಕೆದಾರಹೆಸರು","auth.password":"ಪಾಸ್‌ವರ್ಡ್","auth.signInBtn":"ಸೈನ್ ಇನ್","auth.forgotPassword":"ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರಾ?","auth.username":"ಬಳಕೆದಾರಹೆಸರು","auth.email":"ಇಮೇಲ್","auth.regionLabel":"ಪ್ರದೇಶ (ನಗರ, ದೇಶ)","auth.optionalDash":"— ಐಚ್ಛಿಕ","auth.regionPlaceholder":"ಐಚ್ಛಿಕ — ಉದಾ. Austin, USA","auth.skillLabel":"ಕೌಶಲ್ಯ ಮಟ್ಟ (ನಿಮ್ಮ ಆರಂಭಿಕ ರೇಟಿಂಗ್ ಹೊಂದಿಸುತ್ತದೆ)","auth.skillNew":"ಚೆಸ್‌ಗೆ ಹೊಸಬರು – 400","auth.skillBeginner":"ಆರಂಭಿಕ – 800","auth.skillIntermediate":"ಮಧ್ಯಮ – 1200","auth.skillAdvanced":"ಮುಂದುವರಿದ – 1600","auth.eloHelp":"ELO ಎಂಬುದು ನಿಮ್ಮ ಚೆಸ್ ರೇಟಿಂಗ್ — ಹೆಚ್ಚಿದ್ದರೆ ಬಲಶಾಲಿ. ಹೊಸ ಆಟಗಾರರು ಸಾಮಾನ್ಯವಾಗಿ 400–800 ಸುಮಾರಿಗೆ ಪ್ರಾರಂಭಿಸುತ್ತಾರೆ. ಇದನ್ನು ಬಿಡಬಹುದು — ನಾವು ಪೂರ್ವನಿಯೋಜಿತವಾಗಿ ಆರಂಭಿಕ ಮಟ್ಟವನ್ನು ಹೊಂದಿಸುತ್ತೇವೆ.","auth.createBtn":"ಖಾತೆ ರಚಿಸಿ","auth.languageLabel":"ಭಾಷೆ","auth.or":"ಅಥವಾ","auth.continueGuest":"ಅತಿಥಿಯಾಗಿ ಮುಂದುವರಿಯಿರಿ","auth.guestHint":"ಸೈನ್-ಅಪ್ ಇಲ್ಲ. ನಿಮ್ಮ ಪ್ರಗತಿ ಈ ಸಾಧನದಲ್ಲಿ ಉಳಿಸಲ್ಪಡುತ್ತದೆ — ಸಾಧನಗಳ ನಡುವೆ ಅದನ್ನು ಇರಿಸಿಕೊಳ್ಳಲು ಖಾತೆ ರಚಿಸಿ.","auth.crossDevice":"ನಿಮ್ಮ ಖಾತೆ ನಮ್ಮ ಸರ್ವರ್‌ಗಳಲ್ಲಿ ಸುರಕ್ಷಿತವಾಗಿ ಸಂಗ್ರಹಿಸಲ್ಪಡುತ್ತದೆ, ಆದ್ದರಿಂದ ನಿಮ್ಮ ರೇಟಿಂಗ್ ಮತ್ತು ಟ್ರೋಫಿಗಳು ಸಾಧನಗಳ ನಡುವೆ ನಿಮ್ಮನ್ನು ಅನುಸರಿಸುತ್ತವೆ. ಬಳಕೆದಾರಹೆಸರುಗಳು ಪ್ರತಿ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್‌ನಲ್ಲಿ ವಿಶಿಷ್ಟವಾಗಿವೆ.","settings.title":"ಸೆಟ್ಟಿಂಗ್‌ಗಳು","settings.appearance":"🎨 ಗೋಚರತೆ","settings.boardTheme":"ಬೋರ್ಡ್ ಥೀಮ್","settings.pieceStyle":"ಕಾಯಿ ಶೈಲಿ","settings.language":"🌍 ಭಾಷೆ","settings.languageHint":"ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ. ಇತರ ಭಾಷೆಗಳಲ್ಲಿ ಆಟಗಾರರೊಂದಿಗೆ ಚಾಟ್ ಮಾಡುವುದು ಇನ್ನೂ ಕೆಲಸ ಮಾಡುತ್ತದೆ — playchesstrophies.com ಬ್ರಾಂಡ್ ಹೆಸರು ಯಾವಾಗಲೂ ಇಂಗ್ಲಿಷ್‌ನಲ್ಲೇ ಇರುತ್ತದೆ.","settings.profile":"👤 ಪ್ರೊಫೈಲ್","settings.changePic":"🖼️  ಪ್ರೊಫೈಲ್ ಚಿತ್ರ ಬದಲಾಯಿಸಿ","settings.viewProfile":"✏️  ನನ್ನ ಪ್ರೊಫೈಲ್ ವೀಕ್ಷಿಸಿ","settings.notifications":"🔔 ಅಧಿಸೂಚನೆಗಳು","settings.gameSounds":"ಆಟದ ಧ್ವನಿಗಳು","settings.account":"⚙️ ಖಾತೆ","settings.themeSavedNote":"ನಿಮ್ಮ ಥೀಮ್ ಮತ್ತು ಭಾಷೆ ನಿಮ್ಮ ಪ್ರೊಫೈಲ್‌ನಲ್ಲಿ ಉಳಿಸಲ್ಪಡುತ್ತವೆ — ನೀವು ಸೈನ್ ಇನ್ ಮಾಡಿದ ಪ್ರತಿ ಬಾರಿಯೂ ಅವು ಹಾಗೆಯೇ ಇರುತ್ತವೆ.","settings.changePassword":"🔑  ಪಾಸ್‌ವರ್ಡ್ ಬದಲಾಯಿಸಿ","settings.signOut":"ಸೈನ್ ಔಟ್","toast.langChanged":"ಭಾಷೆ ನವೀಕರಿಸಲಾಗಿದೆ 🌍"};
  STRINGS["ml"] = {"nav.play":"കളിക്കുക","nav.puzzles":"പസിലുകൾ","nav.trophies":"ട്രോഫികൾ","nav.rankings":"റാങ്കിംഗുകൾ","nav.profile":"പ്രൊഫൈൽ","auth.tagline":"കമ്പ്യൂട്ടറിനോട് കളിക്കുക, ദൈനംദിന പസിലുകൾ പരിഹരിക്കുക, സ്ട്രീക്കുകൾ ഉണ്ടാക്കുക, ട്രോഫികൾ നേടുക.","auth.playNow":"▶ ഇപ്പോൾ കളിക്കുക","auth.playNowHint":"സൈൻ-അപ്പ് ആവശ്യമില്ല — ഒറ്റ ടാപ്പിൽ കമ്പ്യൂട്ടറിനെതിരെ ഒരു ഗെയിം ആരംഭിക്കുക. ഓൺലൈനിൽ യഥാർത്ഥ ആളുകളോട് കളിക്കാൻ ഒരു അക്കൗണ്ട് സൃഷ്ടിക്കുക.","auth.tabSignIn":"സൈൻ ഇൻ","auth.tabCreate":"അക്കൗണ്ട് സൃഷ്ടിക്കുക","auth.emailOrUsername":"ഇമെയിൽ അല്ലെങ്കിൽ യൂസർനെയിം","auth.password":"പാസ്‌വേഡ്","auth.signInBtn":"സൈൻ ഇൻ","auth.forgotPassword":"പാസ്‌വേഡ് മറന്നോ?","auth.username":"യൂസർനെയിം","auth.email":"ഇമെയിൽ","auth.regionLabel":"പ്രദേശം (നഗരം, രാജ്യം)","auth.optionalDash":"— ഓപ്ഷണൽ","auth.regionPlaceholder":"ഓപ്ഷണൽ — ഉദാ. Austin, USA","auth.skillLabel":"നൈപുണ്യ നില (നിങ്ങളുടെ ആരംഭ റേറ്റിംഗ് സജ്ജമാക്കുന്നു)","auth.skillNew":"ചെസ്സിൽ പുതിയവർ – 400","auth.skillBeginner":"തുടക്കക്കാരൻ – 800","auth.skillIntermediate":"ഇടത്തരം – 1200","auth.skillAdvanced":"വിപുലമായ – 1600","auth.eloHelp":"ELO എന്നത് നിങ്ങളുടെ ചെസ് റേറ്റിംഗാണ് — കൂടുതലെങ്കിൽ ശക്തമാണ്. പുതിയ കളിക്കാർ സാധാരണയായി 400–800 പരിധിയിൽ ആരംഭിക്കുന്നു. ഇത് വിട്ടേക്കാം — ഞങ്ങൾ സ്ഥിരസ്ഥിതിയായി തുടക്കക്കാരൻ നില സജ്ജമാക്കുന്നു.","auth.createBtn":"അക്കൗണ്ട് സൃഷ്ടിക്കുക","auth.languageLabel":"ഭാഷ","auth.or":"അല്ലെങ്കിൽ","auth.continueGuest":"അതിഥിയായി തുടരുക","auth.guestHint":"സൈൻ-അപ്പ് ഇല്ല. നിങ്ങളുടെ പുരോഗതി ഈ ഉപകരണത്തിൽ സംരക്ഷിക്കപ്പെടും — ഉപകരണങ്ങൾക്കിടയിൽ അത് നിലനിർത്താൻ ഒരു അക്കൗണ്ട് സൃഷ്ടിക്കുക.","auth.crossDevice":"നിങ്ങളുടെ അക്കൗണ്ട് ഞങ്ങളുടെ സെർവറുകളിൽ സുരക്ഷിതമായി സംഭരിക്കപ്പെടുന്നു, അതിനാൽ നിങ്ങളുടെ റേറ്റിംഗും ട്രോഫികളും ഉപകരണങ്ങൾക്കിടയിൽ നിങ്ങളെ പിന്തുടരും. യൂസർനെയിമുകൾ എല്ലാ പ്ലാറ്റ്‌ഫോമിലും അദ്വിതീയമാണ്.","settings.title":"ക്രമീകരണങ്ങൾ","settings.appearance":"🎨 രൂപഭാവം","settings.boardTheme":"ബോർഡ് തീം","settings.pieceStyle":"കരു ശൈലി","settings.language":"🌍 ഭാഷ","settings.languageHint":"നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക. മറ്റ് ഭാഷകളിൽ കളിക്കാരുമായി ചാറ്റ് ചെയ്യുന്നത് ഇപ്പോഴും പ്രവർത്തിക്കുന്നു — playchesstrophies.com ബ്രാൻഡ് നാമം എപ്പോഴും ഇംഗ്ലീഷിൽ തന്നെ തുടരും.","settings.profile":"👤 പ്രൊഫൈൽ","settings.changePic":"🖼️  പ്രൊഫൈൽ ചിത്രം മാറ്റുക","settings.viewProfile":"✏️  എന്റെ പ്രൊഫൈൽ കാണുക","settings.notifications":"🔔 അറിയിപ്പുകൾ","settings.gameSounds":"ഗെയിം ശബ്ദങ്ങൾ","settings.account":"⚙️ അക്കൗണ്ട്","settings.themeSavedNote":"നിങ്ങളുടെ തീമും ഭാഷയും നിങ്ങളുടെ പ്രൊഫൈലിൽ സംരക്ഷിക്കപ്പെടുന്നു — നിങ്ങൾ സൈൻ ഇൻ ചെയ്യുന്ന ഓരോ തവണയും അവ അതേപടി തുടരും.","settings.changePassword":"🔑  പാസ്‌വേഡ് മാറ്റുക","settings.signOut":"സൈൻ ഔട്ട്","toast.langChanged":"ഭാഷ അപ്ഡേറ്റ് ചെയ്തു 🌍"};
  STRINGS["mr"] = {"nav.play":"खेळा","nav.puzzles":"कोडी","nav.trophies":"ट्रॉफी","nav.rankings":"क्रमवारी","nav.profile":"प्रोफाइल","auth.tagline":"संगणकाशी खेळा, रोजची कोडी सोडवा, सलगता वाढवा, ट्रॉफी मिळवा.","auth.playNow":"▶ आता खेळा","auth.playNowHint":"नोंदणीची गरज नाही — एका टॅपमध्ये संगणकाविरुद्ध खेळ सुरू करा. खऱ्या लोकांशी ऑनलाइन खेळण्यासाठी खाते तयार करा.","auth.tabSignIn":"साइन इन","auth.tabCreate":"खाते तयार करा","auth.emailOrUsername":"ईमेल किंवा वापरकर्तानाव","auth.password":"पासवर्ड","auth.signInBtn":"साइन इन","auth.forgotPassword":"पासवर्ड विसरलात?","auth.username":"वापरकर्तानाव","auth.email":"ईमेल","auth.regionLabel":"प्रदेश (शहर, देश)","auth.optionalDash":"— ऐच्छिक","auth.regionPlaceholder":"ऐच्छिक — उदा. ऑस्टिन, अमेरिका","auth.skillLabel":"कौशल्य पातळी (तुमचे सुरुवातीचे रेटिंग ठरवते)","auth.skillNew":"बुद्धिबळात नवीन – 400","auth.skillBeginner":"नवशिक्या – 800","auth.skillIntermediate":"मध्यम – 1200","auth.skillAdvanced":"प्रगत – 1600","auth.eloHelp":"ELO हे तुमचे बुद्धिबळ रेटिंग आहे — जास्त म्हणजे अधिक बलवान. नवीन खेळाडू सहसा 400–800 च्या आसपास सुरू करतात. हे रिकामे ठेवू शकता — आम्ही पूर्वनिर्धारितपणे नवशिक्या घेतो.","auth.createBtn":"खाते तयार करा","auth.languageLabel":"भाषा","auth.or":"किंवा","auth.continueGuest":"पाहुणा म्हणून सुरू ठेवा","auth.guestHint":"नोंदणी नाही. तुमची प्रगती या उपकरणावर जतन केली जाते — सर्व उपकरणांवर ठेवण्यासाठी खाते तयार करा.","auth.crossDevice":"तुमचे खाते आमच्या सर्व्हरवर सुरक्षितपणे साठवले जाते, त्यामुळे तुमचे रेटिंग आणि ट्रॉफी सर्व उपकरणांवर तुमच्यासोबत राहतात. वापरकर्तानावे प्रत्येक प्लॅटफॉर्मवर एकमेव असतात.","settings.title":"सेटिंग्ज","settings.appearance":"🎨 स्वरूप","settings.boardTheme":"बोर्ड थीम","settings.pieceStyle":"मोहऱ्यांची शैली","settings.language":"🌍 भाषा","settings.languageHint":"तुमची भाषा निवडा. इतर भाषांतील खेळाडूंशी गप्पा तरीही चालतात — playchesstrophies.com हे ब्रँड नाव नेहमी इंग्रजीतच राहते.","settings.profile":"👤 प्रोफाइल","settings.changePic":"🖼️  प्रोफाइल चित्र बदला","settings.viewProfile":"✏️  माझे प्रोफाइल पाहा","settings.notifications":"🔔 सूचना","settings.gameSounds":"खेळातील आवाज","settings.account":"⚙️ खाते","settings.themeSavedNote":"तुमची थीम आणि भाषा तुमच्या प्रोफाइलमध्ये जतन केली जाते — प्रत्येक वेळी साइन इन करताना त्या सारख्याच राहतात.","settings.changePassword":"🔑  पासवर्ड बदला","settings.signOut":"साइन आउट","toast.langChanged":"भाषा अद्ययावत झाली 🌍"};
  STRINGS["gu"] = {"nav.play":"રમો","nav.puzzles":"કોયડા","nav.trophies":"ટ્રોફી","nav.rankings":"ક્રમ","nav.profile":"પ્રોફાઇલ","auth.tagline":"કમ્પ્યુટર સામે રમો, રોજના કોયડા ઉકેલો, સ્ટ્રીક બનાવો, ટ્રોફી જીતો.","auth.playNow":"▶ હમણાં રમો","auth.playNowHint":"નોંધણીની જરૂર નથી — એક ટૅપમાં કમ્પ્યુટર સામે રમત શરૂ કરો. ઑનલાઇન વાસ્તવિક લોકો સાથે રમવા માટે ખાતું બનાવો.","auth.tabSignIn":"સાઇન ઇન","auth.tabCreate":"ખાતું બનાવો","auth.emailOrUsername":"ઇમેઇલ અથવા વપરાશકર્તાનામ","auth.password":"પાસવર્ડ","auth.signInBtn":"સાઇન ઇન","auth.forgotPassword":"પાસવર્ડ ભૂલી ગયા?","auth.username":"વપરાશકર્તાનામ","auth.email":"ઇમેઇલ","auth.regionLabel":"પ્રદેશ (શહેર, દેશ)","auth.optionalDash":"— વૈકલ્પિક","auth.regionPlaceholder":"વૈકલ્પિક — દા.ત. ઑસ્ટિન, અમેરિકા","auth.skillLabel":"કૌશલ્ય સ્તર (તમારું શરૂઆતનું રેટિંગ નક્કી કરે છે)","auth.skillNew":"ચેસમાં નવા – 400","auth.skillBeginner":"શરૂઆતી – 800","auth.skillIntermediate":"મધ્યમ – 1200","auth.skillAdvanced":"પ્રગત – 1600","auth.eloHelp":"ELO એ તમારું ચેસ રેટિંગ છે — વધારે એટલે વધુ મજબૂત. નવા ખેલાડીઓ સામાન્ય રીતે 400–800 આસપાસ શરૂ કરે છે. તમે આ ખાલી છોડી શકો છો — અમે મૂળભૂત રીતે શરૂઆતી લઈએ છીએ.","auth.createBtn":"ખાતું બનાવો","auth.languageLabel":"ભાષા","auth.or":"અથવા","auth.continueGuest":"મહેમાન તરીકે ચાલુ રાખો","auth.guestHint":"નોંધણી નહીં. તમારી પ્રગતિ આ ઉપકરણ પર સચવાય છે — બધા ઉપકરણો પર રાખવા માટે ખાતું બનાવો.","auth.crossDevice":"તમારું ખાતું અમારા સર્વર પર સુરક્ષિત રીતે સંગ્રહિત થાય છે, તેથી તમારું રેટિંગ અને ટ્રોફી બધા ઉપકરણો પર તમારી સાથે રહે છે. વપરાશકર્તાનામ દરેક પ્લેટફોર્મ પર અનન્ય હોય છે.","settings.title":"સેટિંગ્સ","settings.appearance":"🎨 દેખાવ","settings.boardTheme":"બોર્ડ થીમ","settings.pieceStyle":"મહોરાંની શૈલી","settings.language":"🌍 ભાષા","settings.languageHint":"તમારી ભાષા પસંદ કરો. અન્ય ભાષાઓના ખેલાડીઓ સાથે ચેટ હજુ પણ ચાલે છે — playchesstrophies.com બ્રાન્ડ નામ હંમેશા અંગ્રેજીમાં જ રહે છે.","settings.profile":"👤 પ્રોફાઇલ","settings.changePic":"🖼️  પ્રોફાઇલ ચિત્ર બદલો","settings.viewProfile":"✏️  મારી પ્રોફાઇલ જુઓ","settings.notifications":"🔔 સૂચનાઓ","settings.gameSounds":"રમતના અવાજ","settings.account":"⚙️ ખાતું","settings.themeSavedNote":"તમારી થીમ અને ભાષા તમારી પ્રોફાઇલમાં સચવાય છે — દર વખતે સાઇન ઇન કરતી વખતે તે સમાન જ રહે છે.","settings.changePassword":"🔑  પાસવર્ડ બદલો","settings.signOut":"સાઇન આઉટ","toast.langChanged":"ભાષા અપડેટ થઈ 🌍"};
  STRINGS["pa"] = {"nav.play":"ਖੇਡੋ","nav.puzzles":"ਬੁਝਾਰਤਾਂ","nav.trophies":"ਟਰਾਫੀਆਂ","nav.rankings":"ਦਰਜਾਬੰਦੀ","nav.profile":"ਪ੍ਰੋਫਾਈਲ","auth.tagline":"ਕੰਪਿਊਟਰ ਨਾਲ ਖੇਡੋ, ਰੋਜ਼ਾਨਾ ਬੁਝਾਰਤਾਂ ਹੱਲ ਕਰੋ, ਲੜੀਆਂ ਬਣਾਓ, ਟਰਾਫੀਆਂ ਜਿੱਤੋ.","auth.playNow":"▶ ਹੁਣੇ ਖੇਡੋ","auth.playNowHint":"ਕਿਸੇ ਸਾਈਨ-ਅੱਪ ਦੀ ਲੋੜ ਨਹੀਂ — ਇੱਕ ਟੈਪ ਵਿੱਚ ਕੰਪਿਊਟਰ ਖ਼ਿਲਾਫ਼ ਖੇਡ ਸ਼ੁਰੂ ਕਰੋ. ਅਸਲ ਲੋਕਾਂ ਨਾਲ ਆਨਲਾਈਨ ਖੇਡਣ ਲਈ ਖਾਤਾ ਬਣਾਓ.","auth.tabSignIn":"ਸਾਈਨ ਇਨ","auth.tabCreate":"ਖਾਤਾ ਬਣਾਓ","auth.emailOrUsername":"ਈਮੇਲ ਜਾਂ ਵਰਤੋਂਕਾਰ ਨਾਮ","auth.password":"ਪਾਸਵਰਡ","auth.signInBtn":"ਸਾਈਨ ਇਨ","auth.forgotPassword":"ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?","auth.username":"ਵਰਤੋਂਕਾਰ ਨਾਮ","auth.email":"ਈਮੇਲ","auth.regionLabel":"ਖੇਤਰ (ਸ਼ਹਿਰ, ਦੇਸ਼)","auth.optionalDash":"— ਵਿਕਲਪਿਕ","auth.regionPlaceholder":"ਵਿਕਲਪਿਕ — ਜਿਵੇਂ ਆਸਟਿਨ, ਅਮਰੀਕਾ","auth.skillLabel":"ਹੁਨਰ ਪੱਧਰ (ਤੁਹਾਡੀ ਸ਼ੁਰੂਆਤੀ ਰੇਟਿੰਗ ਤੈਅ ਕਰਦਾ ਹੈ)","auth.skillNew":"ਸ਼ਤਰੰਜ ਵਿੱਚ ਨਵੇਂ – 400","auth.skillBeginner":"ਸ਼ੁਰੂਆਤੀ – 800","auth.skillIntermediate":"ਦਰਮਿਆਨੇ – 1200","auth.skillAdvanced":"ਉੱਨਤ – 1600","auth.eloHelp":"ELO ਤੁਹਾਡੀ ਸ਼ਤਰੰਜ ਰੇਟਿੰਗ ਹੈ — ਵੱਧ ਦਾ ਮਤਲਬ ਵਧੇਰੇ ਮਜ਼ਬੂਤ. ਨਵੇਂ ਖਿਡਾਰੀ ਆਮ ਤੌਰ 'ਤੇ 400–800 ਦੇ ਆਸਪਾਸ ਸ਼ੁਰੂ ਕਰਦੇ ਹਨ. ਤੁਸੀਂ ਇਸਨੂੰ ਖਾਲੀ ਛੱਡ ਸਕਦੇ ਹੋ — ਅਸੀਂ ਮੂਲ ਰੂਪ ਵਿੱਚ ਸ਼ੁਰੂਆਤੀ ਲੈਂਦੇ ਹਾਂ.","auth.createBtn":"ਖਾਤਾ ਬਣਾਓ","auth.languageLabel":"ਭਾਸ਼ਾ","auth.or":"ਜਾਂ","auth.continueGuest":"ਮਹਿਮਾਨ ਵਜੋਂ ਜਾਰੀ ਰੱਖੋ","auth.guestHint":"ਕੋਈ ਸਾਈਨ-ਅੱਪ ਨਹੀਂ. ਤੁਹਾਡੀ ਤਰੱਕੀ ਇਸ ਡਿਵਾਈਸ 'ਤੇ ਸੰਭਾਲੀ ਜਾਂਦੀ ਹੈ — ਇਸਨੂੰ ਸਾਰੀਆਂ ਡਿਵਾਈਸਾਂ 'ਤੇ ਰੱਖਣ ਲਈ ਖਾਤਾ ਬਣਾਓ.","auth.crossDevice":"ਤੁਹਾਡਾ ਖਾਤਾ ਸਾਡੇ ਸਰਵਰਾਂ 'ਤੇ ਸੁਰੱਖਿਅਤ ਢੰਗ ਨਾਲ ਸਟੋਰ ਕੀਤਾ ਜਾਂਦਾ ਹੈ, ਇਸ ਲਈ ਤੁਹਾਡੀ ਰੇਟਿੰਗ ਅਤੇ ਟਰਾਫੀਆਂ ਸਾਰੀਆਂ ਡਿਵਾਈਸਾਂ 'ਤੇ ਤੁਹਾਡੇ ਨਾਲ ਚੱਲਦੀਆਂ ਹਨ. ਵਰਤੋਂਕਾਰ ਨਾਮ ਹਰ ਪਲੇਟਫਾਰਮ 'ਤੇ ਵਿਲੱਖਣ ਹੁੰਦੇ ਹਨ.","settings.title":"ਸੈਟਿੰਗਾਂ","settings.appearance":"🎨 ਦਿੱਖ","settings.boardTheme":"ਬੋਰਡ ਥੀਮ","settings.pieceStyle":"ਮੋਹਰਿਆਂ ਦੀ ਸ਼ੈਲੀ","settings.language":"🌍 ਭਾਸ਼ਾ","settings.languageHint":"ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ. ਹੋਰ ਭਾਸ਼ਾਵਾਂ ਦੇ ਖਿਡਾਰੀਆਂ ਨਾਲ ਗੱਲਬਾਤ ਫਿਰ ਵੀ ਚੱਲਦੀ ਹੈ — playchesstrophies.com ਬ੍ਰਾਂਡ ਨਾਮ ਹਮੇਸ਼ਾ ਅੰਗਰੇਜ਼ੀ ਵਿੱਚ ਹੀ ਰਹਿੰਦਾ ਹੈ.","settings.profile":"👤 ਪ੍ਰੋਫਾਈਲ","settings.changePic":"🖼️  ਪ੍ਰੋਫਾਈਲ ਤਸਵੀਰ ਬਦਲੋ","settings.viewProfile":"✏️  ਮੇਰੀ ਪ੍ਰੋਫਾਈਲ ਵੇਖੋ","settings.notifications":"🔔 ਸੂਚਨਾਵਾਂ","settings.gameSounds":"ਖੇਡ ਦੀਆਂ ਆਵਾਜ਼ਾਂ","settings.account":"⚙️ ਖਾਤਾ","settings.themeSavedNote":"ਤੁਹਾਡੀ ਥੀਮ ਅਤੇ ਭਾਸ਼ਾ ਤੁਹਾਡੀ ਪ੍ਰੋਫਾਈਲ ਵਿੱਚ ਸੰਭਾਲੀ ਜਾਂਦੀ ਹੈ — ਹਰ ਵਾਰ ਸਾਈਨ ਇਨ ਕਰਨ 'ਤੇ ਇਹ ਉਹੀ ਰਹਿੰਦੀਆਂ ਹਨ.","settings.changePassword":"🔑  ਪਾਸਵਰਡ ਬਦਲੋ","settings.signOut":"ਸਾਈਨ ਆਉਟ","toast.langChanged":"ਭਾਸ਼ਾ ਅੱਪਡੇਟ ਹੋਈ 🌍"};
  STRINGS["ar"] = {"nav.play":"العب","nav.puzzles":"الألغاز","nav.trophies":"الجوائز","nav.rankings":"التصنيفات","nav.profile":"الملف الشخصي","auth.tagline":"العب ضد الكمبيوتر، وحل الألغاز اليومية، وحقق سلاسل الفوز، واكسب الجوائز.","auth.playNow":"▶ العب الآن","auth.playNowHint":"لا حاجة للتسجيل — ابدأ مباراة ضد الكمبيوتر بنقرة واحدة. أنشئ حسابًا للعب مع أشخاص حقيقيين عبر الإنترنت.","auth.tabSignIn":"تسجيل الدخول","auth.tabCreate":"إنشاء حساب","auth.emailOrUsername":"البريد الإلكتروني أو اسم المستخدم","auth.password":"كلمة المرور","auth.signInBtn":"تسجيل الدخول","auth.forgotPassword":"هل نسيت كلمة المرور؟","auth.username":"اسم المستخدم","auth.email":"البريد الإلكتروني","auth.regionLabel":"المنطقة (المدينة، الدولة)","auth.optionalDash":"— اختياري","auth.regionPlaceholder":"اختياري — مثال: أوستن، الولايات المتحدة","auth.skillLabel":"مستوى المهارة (يحدد تصنيفك المبدئي)","auth.skillNew":"جديد في الشطرنج – 400","auth.skillBeginner":"مبتدئ – 800","auth.skillIntermediate":"متوسط – 1200","auth.skillAdvanced":"متقدم – 1600","auth.eloHelp":"ELO هو تصنيفك في الشطرنج — كلما ارتفع كنت أقوى. عادةً ما يبدأ اللاعبون الجدد حول 400–800. يمكنك ترك هذا الحقل — وسنعتمد المستوى المبتدئ افتراضيًا.","auth.createBtn":"إنشاء حساب","auth.languageLabel":"اللغة","auth.or":"أو","auth.continueGuest":"المتابعة كضيف","auth.guestHint":"بدون تسجيل. يُحفظ تقدمك على هذا الجهاز — أنشئ حسابًا للاحتفاظ به عبر جميع أجهزتك.","auth.crossDevice":"حسابك مخزّن بأمان على خوادمنا، لذا يرافقك تصنيفك وجوائزك عبر جميع الأجهزة. أسماء المستخدمين فريدة عبر كل المنصات.","settings.title":"الإعدادات","settings.appearance":"🎨 المظهر","settings.boardTheme":"سمة الرقعة","settings.pieceStyle":"نمط القطع","settings.language":"🌍 اللغة","settings.languageHint":"اختر لغتك. تظل الدردشة مع اللاعبين بلغات أخرى متاحة — ويبقى اسم العلامة التجارية playchesstrophies.com بالإنجليزية دائمًا.","settings.profile":"👤 الملف الشخصي","settings.changePic":"🖼️  تغيير صورة الملف الشخصي","settings.viewProfile":"✏️  عرض ملفي الشخصي","settings.notifications":"🔔 الإشعارات","settings.gameSounds":"أصوات اللعبة","settings.account":"⚙️ الحساب","settings.themeSavedNote":"يتم حفظ سمتك ولغتك في ملفك الشخصي — تبقى كما هي في كل مرة تسجل فيها الدخول.","settings.changePassword":"🔑  تغيير كلمة المرور","settings.signOut":"تسجيل الخروج","toast.langChanged":"تم تحديث اللغة 🌍"};
  STRINGS["ur"] = {"nav.play":"کھیلیں","nav.puzzles":"پہیلیاں","nav.trophies":"ٹرافیاں","nav.rankings":"درجہ بندی","nav.profile":"پروفائل","auth.tagline":"کمپیوٹر کے خلاف کھیلیں، روزانہ کی پہیلیاں حل کریں، تسلسل بنائیں، اور ٹرافیاں جیتیں۔","auth.playNow":"▶ ابھی کھیلیں","auth.playNowHint":"سائن اپ کی ضرورت نہیں — ایک ٹیپ میں کمپیوٹر کے خلاف کھیل شروع کریں۔ آن لائن حقیقی لوگوں کے ساتھ کھیلنے کے لیے اکاؤنٹ بنائیں۔","auth.tabSignIn":"سائن اِن","auth.tabCreate":"اکاؤنٹ بنائیں","auth.emailOrUsername":"ای میل یا صارف نام","auth.password":"پاس ورڈ","auth.signInBtn":"سائن اِن","auth.forgotPassword":"پاس ورڈ بھول گئے؟","auth.username":"صارف نام","auth.email":"ای میل","auth.regionLabel":"علاقہ (شہر، ملک)","auth.optionalDash":"— اختیاری","auth.regionPlaceholder":"اختیاری — مثلاً آسٹن، امریکہ","auth.skillLabel":"مہارت کی سطح (آپ کی ابتدائی ریٹنگ طے کرتی ہے)","auth.skillNew":"شطرنج میں نئے – 400","auth.skillBeginner":"مبتدی – 800","auth.skillIntermediate":"درمیانہ – 1200","auth.skillAdvanced":"ماہر – 1600","auth.eloHelp":"ELO آپ کی شطرنج ریٹنگ ہے — زیادہ کا مطلب مضبوط تر۔ نئے کھلاڑی عموماً 400–800 کے قریب شروع کرتے ہیں۔ آپ اسے چھوڑ سکتے ہیں — ہم بطورِ ڈیفالٹ مبتدی رکھتے ہیں۔","auth.createBtn":"اکاؤنٹ بنائیں","auth.languageLabel":"زبان","auth.or":"یا","auth.continueGuest":"بطورِ مہمان جاری رکھیں","auth.guestHint":"کوئی سائن اپ نہیں۔ آپ کی پیش رفت اِسی ڈیوائس پر محفوظ ہوتی ہے — اسے تمام ڈیوائسز پر برقرار رکھنے کے لیے اکاؤنٹ بنائیں۔","auth.crossDevice":"آپ کا اکاؤنٹ ہمارے سرورز پر محفوظ طریقے سے محفوظ ہے، اس لیے آپ کی ریٹنگ اور ٹرافیاں تمام ڈیوائسز پر آپ کے ساتھ رہتی ہیں۔ صارف نام ہر پلیٹ فارم پر منفرد ہوتے ہیں۔","settings.title":"ترتیبات","settings.appearance":"🎨 ظاہری شکل","settings.boardTheme":"بورڈ تھیم","settings.pieceStyle":"مہروں کا انداز","settings.language":"🌍 زبان","settings.languageHint":"اپنی زبان منتخب کریں۔ دوسری زبانوں میں کھلاڑیوں کے ساتھ چیٹ پھر بھی کام کرتی ہے — playchesstrophies.com برانڈ کا نام ہمیشہ انگریزی میں ہی رہتا ہے۔","settings.profile":"👤 پروفائل","settings.changePic":"🖼️  پروفائل تصویر تبدیل کریں","settings.viewProfile":"✏️  میری پروفائل دیکھیں","settings.notifications":"🔔 اطلاعات","settings.gameSounds":"گیم کی آوازیں","settings.account":"⚙️ اکاؤنٹ","settings.themeSavedNote":"آپ کی تھیم اور زبان آپ کی پروفائل میں محفوظ ہو جاتی ہیں — ہر بار سائن اِن کرنے پر یہ ویسی ہی رہتی ہیں۔","settings.changePassword":"🔑  پاس ورڈ تبدیل کریں","settings.signOut":"سائن آؤٹ","toast.langChanged":"زبان اپ ڈیٹ ہو گئی 🌍"};
  /* </LANGS> */

  // ---- Engine -------------------------------------------------------------
  function supported(code) {
    for (var i = 0; i < LANGS.length; i++) if (LANGS[i].code === code) return true;
    return false;
  }
  function dirFor(code) {
    for (var i = 0; i < LANGS.length; i++) if (LANGS[i].code === code) return LANGS[i].dir || 'ltr';
    return 'ltr';
  }
  function detect() {
    try { var s = localStorage.getItem(STORE_KEY); if (s && supported(s)) return s; } catch (e) {}
    try {
      var n = String(navigator.language || 'en').toLowerCase();
      if (supported(n)) return n;
      var two = n.split('-')[0];
      if (supported(two)) return two;
      if (two === 'zh') return 'zh';
      if (two === 'fil') return 'tl';
    } catch (e) {}
    return 'en';
  }

  var current = detect();

  // Translate a key with optional {var} interpolation. Falls back to English,
  // then to the raw key — never returns blank.
  function t(key, vars) {
    var table = STRINGS[current] || EN;
    var s = table[key];
    if (s == null) s = EN[key];
    if (s == null) s = key;
    if (vars) {
      s = s.replace(/\{(\w+)\}/g, function (m, k) { return vars[k] != null ? String(vars[k]) : m; });
    }
    return s;
  }

  // Swap every tagged node under `root` to the active language.
  function apply(root) {
    root = root || document;
    var i, els;
    els = root.querySelectorAll('[data-i18n]');
    for (i = 0; i < els.length; i++) els[i].textContent = t(els[i].getAttribute('data-i18n'));
    els = root.querySelectorAll('[data-i18n-ph]');
    for (i = 0; i < els.length; i++) els[i].setAttribute('placeholder', t(els[i].getAttribute('data-i18n-ph')));
    els = root.querySelectorAll('[data-i18n-aria]');
    for (i = 0; i < els.length; i++) els[i].setAttribute('aria-label', t(els[i].getAttribute('data-i18n-aria')));
    try {
      document.documentElement.lang = current;
      document.documentElement.dir = dirFor(current);
    } catch (e) {}
  }

  // Switch language: persist locally, re-render, broadcast.
  function setLang(code, opts) {
    if (!supported(code)) code = 'en';
    if (code === current && !(opts && opts.force)) { apply(document); return; }
    current = code;
    try { localStorage.setItem(STORE_KEY, code); } catch (e) {}
    apply(document);
    try { window.dispatchEvent(new CustomEvent('ct:langchange', { detail: { lang: code } })); } catch (e) {}
  }
  function getLang() { return current; }

  // Populate a <select> with the language options (native names).
  function fillSelect(sel, selected) {
    if (!sel) return;
    var html = '';
    for (var i = 0; i < LANGS.length; i++) {
      var l = LANGS[i];
      var on = (l.code === (selected || current)) ? ' selected' : '';
      html += '<option value="' + l.code + '"' + on + '>' + l.name + '</option>';
    }
    sel.innerHTML = html;
  }

  // Allow the per-language dictionary blocks (below) to register themselves.
  function registerLang(code, dict) { STRINGS[code] = dict; }

  window.CT_i18n = {
    t: t, apply: apply, setLang: setLang, getLang: getLang,
    langs: LANGS, supported: supported, dir: dirFor, fillSelect: fillSelect,
    registerLang: registerLang, _strings: STRINGS
  };

  // Apply ASAP. As a `defer` script the DOM is already parsed when we run, so
  // this catches first paint; re-run on DOMContentLoaded as a belt-and-braces.
  function boot() { apply(document); }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot);
  else boot();
})();
